version: '3.6'

services:
  nginx:
    image: nginx:1
    volumes:
      - ./nginx:/var/log/nginx
    ports:
      - 8080:80
    environment:
      - NGINX_HOST=example.com
      - NGINX_PORT=80

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        STACK_VERSION: $STACK_VERSION
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - 9200:9200
    networks:
      - esnet

  logstash:
    build:
      context: logstash/
      args:
        STACK_VERSION: $STACK_VERSION
    environment:
      - 'LS_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - 5044:5044
    networks:
      - esnet
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        STACK_VERSION: $STACK_VERSION
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: filebeat/
      args:
        STACK_VERSION: $STACK_VERSION
    volumes:
      - ./nginx:/var/log/nginx
    networks:
      - esnet
    depends_on:
      - logstash

volumes:
  esdata:
    
networks:
  esnet:
