version: '3.3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - logdata:/var/log/nginx
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=example.com
      - NGINX_PORT=80

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - type: bind
        source: ./sysctl.conf
        target: /etc/sysctl.conf
        read_only: true
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    networks:
      - esnet

  logstash:
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    volumes:
      - type: bind
        source: ./logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
        read_only: true
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 5044:5044
    networks:
      - esnet
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    ports:
      - 8000:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:${STACK_VERSION}
    volumes:
      - logdata:/var/log/nginx
      - type: bind
        source: ./filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
    networks:
      - esnet
    depends_on:
      - logstash

volumes:
  esdata:
    driver: local
  logdata:
    driver: local
    
networks:
  esnet:
