name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker images
      run: docker-compose build
    - name: Start containers
      run: docker-compose up -d
    - name: Stop containers
      run: docker-compose down -v
